### ISSUE TITLE
Segmentation Fault - Unknown EGL Driver

### ISSUE THREAD

**Issue by milisarge** [CuarzoSoftware/Louvre#57]
Hi, i trying Louvre in my Qemu Linux box (-vga virtio option), building from source code, but i am getting the error at below.

[EGL driver name: Unknown.](https://0x0.st/XPP3.log)

With same enviroment Labwc, Wayfire seems working but Louvre gives segmentation fault

**Comment by ehopperdietzel** [comment]
Hi, is that the complete log? Could you please provide me with the GDB log of the segfault point or inform me about the QEMU setup you're using? The missing EGL driver name is common and isn't a problem.

**Comment by milisarge** [comment]
`qemu-system-x86_64 --enable-kvm -vga qxl` and `-vga virtio` parameters 
additionally dri backends and my video card info:

![resim](https://github.com/CuarzoSoftware/Louvre/assets/15840648/f640a091-2329-43e0-8afd-587131d3d8ae)

**Comment by ehopperdietzel** [comment]
Thanks, I think the segfault was caused by a call to an EGL function that is not supported by virtio. I've added some checks, and now it should work fine, it works for me running Fedora inside qemu. The changes are in the 2.0.0 branch. Also, if you notice any unusual behaviour in the examples, specially when clicking windows it's likely because I'm currently implementing some features that are not yet completed.

**Comment by milisarge** [comment]
Thank you for update, i tired also and it works with `-vga qxl` , but as you mentioned, keyboard and mouse events don't work for now.

**Comment by ehopperdietzel** [comment]
Thank goodness you mentioned it. It's true, I noticed that only keyboard events are functioning. When I press fn + F1, weston-terminal launches as expected, but there are no pointer events. I've just looked into the [Libinput doc](https://wayland.freedesktop.org/libinput/doc/latest/what-is-libinput.html#handled-device-types) and realized that there are relative and absolute pointer events. The documentation even indicates that absolute events are used in contexts like QEMU and VBox. Currently, Louvre only handles relative events. I'll be adding support for absolute events shortly, and I'll keep you informed.

**Comment by ehopperdietzel** [comment]
It's now working (branch 2.0.0). However, there are still some issues with the cursor hotspot. I guess this is due to SRM not using the hotspot property of hardware cursor planes in DRM/KMS, which I always thought was kind of useless, but now I know its use case. When running on a real machine, Louvre controls cursor movement and properly adjusts the hotspot, but in this case, QEMU overrides it.
