### ISSUE TITLE
Double visible mouse pointer

### ISSUE THREAD

**Issue by milisarge** [CuarzoSoftware/Louvre#64]
As you see in [video](https://0x0.st/XcOL.mp4) after logout from Louvre, when i enter again to my Labwc session, it shows two pointer of a mouse.

**Comment by ehopperdietzel** [comment]
Hmm it looks like Labwc is not setting the harware cursor plane and its rendering it instead, or maybe using 2.
I guess this could be actually a Labwc bug but since it seems to be running inside a virtual environment I am not sure.

To fix this, you could try hiding the cursor before leaving the Louvre session:

#### Louvre Views Seat.cpp
```cpp
void Seat::enabledChanged()
{
    if (!enabled())
    {
        cursor()->setVisible(false);
        return;
    }

   ...
}
```

If that doesn't work, you could disable hardware composition for all outputs:

#### Louvre Views Output.cpp
```cpp
void Output::initializeGL()
{
    cursor()->enableHwCompositing(this, false);

   ...
}
```

**Comment by milisarge** [comment]
both of ways don't work, still there are two visible pointers

**Comment by milisarge** [comment]
After discussion with Labwc guys, we noticed that it is [Qemu bug](https://gitlab.freedesktop.org/wlroots/wlroots/-/issues/3731) for now, i resolved it with `-vga virtio -display sdl,show-cursor=off`

**Comment by ehopperdietzel** [comment]
Ok, thanks for letting me know, so does this happen when switching between other compositors as well? And what are you building? It looks interesting

**Comment by milisarge** [comment]
I am the maintainer of [Milis Linux](https://milislinux.gitlab.io/en/) project, so far now, we have been using wlroots based compositors as WM, so have not noticed such a bug in switching between them. Well, we are trying to setup a composition of desktop environment and Louvre is the new base as alternative of Wlroots.

**Comment by ehopperdietzel** [comment]
Nice! I see it has its own package manager and init system, that must be a lot of work! Can it be tested on real hardware? And does it support other languages apart from Turkish?

> we have been using wlroots based compositors as WM, so have not noticed such a bug in switching between them

There is one last option, maybe setting the **SRM_FORCE_LEGACY_API**=0 env could fix it.

**Comment by milisarge** [comment]
Yes, it has been used as daily Linux system since 2016 with different versions, current version is [2.3](https://milislinux.gitlab.io/en/download/) and you can test it, Qemu is one of my test environment so i am testing first with it, English the other language option for the present.

`SRM_FORCE_LEGACY_API=0` env solved Labwc side so no twice pointer but the pointer disappeared at Louvre side. [video](https://0x0.st/XcEF.mp4)

**Comment by ehopperdietzel** [comment]
> Yes, it has been used as daily Linux system since 2016 with different versions, current version is [2.3](https://milislinux.gitlab.io/en/download/) and you can test it, Qemu is one of my test environment so i am testing first with it, English the other language option for the present.

Perfect! I'll give it a try and then let you know how it went.

> SRM_FORCE_LEGACY_API=0 env solved Labwc side so no twice pointer but the pointer disappeared at Louvre side. [video](https://0x0.st/XcEF.mp4)

Hmm, glad you noticed it. That must be an SRM bug, so I definitely need to take a look at that.

**Comment by ehopperdietzel** [comment]
I tested Milis, and it works perfectly, great work! I only had problems with my Wi-Fi card, but that happens in almost every distro since it requires proprietary drivers. Also, neither Labwc nor Wayfire set the scale factor of HiDPI displays to 2 by default, which is just a small detail and I'm sure it can be easily configured.

Additionally, I think I fixed the cursor issue in SRM. The changes are in the [devel branch](https://github.com/CuarzoSoftware/SRM/tree/devel) if you want to test them. I think I wasn't properly handling cases where the first Atomic commit failed.

**Comment by milisarge** [comment]
you can scale display from [settings](https://0x0.st/XAYZ.mp4)

i updated the Louvre with SRM-devel, but still pointer disappears at Louvre.

**Comment by ehopperdietzel** [comment]
> you can scale display from [settings](https://0x0.st/XAYZ.mp4)

Yes, I experimented with that. I just wanted to suggest that from a user perspective, it would be nice if the default scale could be set to 1.75 or 2 on HiDPI displays (e.g. DPI >= 200), as everything appears too small with a scale factor of 1. By the way, I plan to add the same protocol for controlling outputs to Louvre soon so that the panel will also work with Louvre compositors.

> i updated the Louvre with SRM-devel, but still pointer disappears at Louvre.

Hmm :( I'll need to check that again. At least on real hardware, it seems to work fine, but I haven't tested it inside Qemu. Thanks, by the way, for testing it.

**Comment by ehopperdietzel** [comment]
Hi again @milisarge, I attempted to implement hiding cursor planes before session switching. However, it appears that libseat drops DRM permissions to the compositor either before or simultaneously with notifying the TTY switch, preventing Louvre from hiding it. Nonetheless, I have updated SRM so that the cursor should now be restored when using the atomic API (SRM_FORCE_LEGACY_API=0).

**Comment by milisarge** [comment]
i updated Louvre to 2.8.0 and compatible SRM with it. But still mouse pointer seems disappeared  (SRM_FORCE_LEGACY_API=0). By the way SRM-devel branch is not compatible with 2.8.0 so i couldn't try it.

**Comment by milisarge** [comment]
But i catched double pointer issue when i start the wf-recorder process.

https://github.com/user-attachments/assets/80df35fd-8c26-4358-bd39-347520309699

**Comment by ehopperdietzel** [comment]
> But i catched double pointer issue when i start the wf-recorder process.

Is that happening only inside QEMU?

**Comment by ehopperdietzel** [comment]
I've just added the **SRM_DISABLE_CURSOR** env, setting it to 1 should fix it.

**Comment by milisarge** [comment]
finally, it is solved, works like charm :) thanks for your effort

**Comment by ehopperdietzel** [comment]
Hi @milisarge, the `wlr-output-management` protocol is now available, which should enable your distro's display configuration panel to work with Louvre.

**Comment by ehopperdietzel** [comment]
Glad to hear that @milisarge ! Thanks for trying it!
