### ISSUE TITLE
[q] Why was the license changed? It is no longer possible to link Louvre statically, or distribute bundles (ie, appimages) with Louvre

### ISSUE THREAD

**Issue by xplshn** [CuarzoSoftware/Louvre#89]
Please reconsider this change, it just makes working with Louvre legally cumbersome and incompatible with other projects

**Comment by 2xsaiko** [comment]
This is a common myth. It is absolutely possible link LGPL libraries statically if you do it in a way that ensures the program can be relinked with a different version of Louvre, like if the final program is GPL itself or otherwise for example by distributing the compiled object files used to link the final program.

**Comment by ehopperdietzel** [comment]
I want to ensure that I'll be able to see any improvements made by others before I proceed with adding the following features. Previous versions were released under MIT, so you are welcome to continue using them.

**Comment by xplshn** [comment]
What a shame
